port: 4232
http_port: 8232

server_name: l1

cluster: {
  name: L
}

leafnodes {
  remotes [
    { urls: ["nats-leaf://l:x@localhost:7422"], account: EDGE }
  ]
}

accounts: {
  EDGE: {
    users: [ 
      { user: e, password: x }
    ]
  }
}
