port: 4222
http_port: 8222

server_name: hub

cluster: {
  name: HUB
}

leafnodes {
  port: 7422
}

accounts: {
  APP: {
    users: [ 
      { user: a, password: x }
      { user: l, password: x }
    ]
  }
}
