port: 4222
http_port: 8222

server_name: hub

cluster: {
  name: HUB
}

leafnodes {
  isolate: false

  remotes [
    { urls: ["nats-leaf://l:x@localhost:7432"], account: APP, hub: true }
    { urls: ["nats-leaf://l:x@localhost:7442"], account: APP, hub: true }
    { urls: ["nats-leaf://l:x@localhost:7452"], account: APP, hub: true, isolate: true }
  ]
}

accounts: {
  APP: {
    users: [ 
      { user: a, password: x }
    ]
  }
}
no_auth_user: a
