port: 4252
http_port: 8252

server_name: l3

cluster: {
  name: L3
}

leafnodes {
  remotes [
    { urls: ["nats-leaf://l3:x@localhost:7422"], account: EDGE,
      deny_imports: [ "nosub.>" ], deny_exports: [ "nopub.>" ] }
  ]
}

accounts: {
  EDGE: {
    users: [ 
      { user: e, password: x }
    ]
  }
}
