port: 4242
http_port: 8242

server_name: l2

cluster: {
  name: L2
}

leafnodes {
  remotes [
    { urls: ["nats-leaf://l:x@localhost:7422"], account: EDGE }
  ]
}

accounts: {
  EDGE: {
    users: [ 
      { user: e, password: x }
    ]
  }
}
