port: 4252
http_port: 8252

server_name: l3

cluster: {
  name: L3
}

leafnodes {
  port: 7442
}

accounts: {
  EDGE: {
    users: [ 
      { user: e, password: x }
      { user: l, password: x }
    ]
  }
}
