port: 4262
http_port: 8262

server_name: l3gate

cluster: {
  name: L3GATE
}

leafnodes {
  remotes [
    # leaf to hub
    { urls: ["nats-leaf://l:x@localhost:7422"], account: GATE }
    { urls: ["nats-leaf://sl:x@localhost:7422"], account: SYS }

    # leaf to leaf 3
    { urls: ["nats-leaf://el:x@localhost:7452"], account: GATE, hub: true }
    { urls: ["nats-leaf://sl:x@localhost:7452"], account: SYS, hub: true }
  ]
}

accounts: {
  GATE: {
  }
  SYS: {
  }
}
system_account: SYS
