port: 4222
http_port: 8222

server_name: hub

cluster: {
  name: HUB
}

leafnodes {
  port: 7422
  isolate: true
}

accounts: {
  APP: {
    users: [ 
      { user: a, password: x }

      { user: l1, password:x, permissions: { 
        publish: { allow: [
          "_INBOX.>"
          "$JSC.R.>"
          "$JS.S.>"
          "$JS.M.>"
          ] },  
        subscribe: { allow: [
          "$JS.FC.>"
          "$JS.ACK.>"
          "$JS.L1.API.>"
          ] } } 
      }
      
      { user: l2, password:x, permissions: { 
        publish: { allow: [
          "_INBOX.>"
          "$JSC.R.>"
          "$JS.S.>"
          "$JS.M.>"
          ] },  
        subscribe: { allow: [
          "$JS.FC.>"
          "$JS.ACK.>"
          "$JS.L2.API.INFO"
          "$JS.L2.API.STREAM.INFO.TELEMETRY"
          "$JS.L2.API.CONSUMER.*.TELEMETRY"
          "$JS.L2.API.CONSUMER.*.TELEMETRY.>"
          "$JS.L2.API.CONSUMER.MSG.NEXT.TELEMETRY.>"

#          "$JS.L2.API.STREAM.MSG.GET.TELEMETRY"
#          "$JS.L2.API.DIRECT.GET.TELEMETRY.>"
          ] } } 
      }

      { user: l3, password:x, permissions: { 
        publish: { allow: [
          "_INBOX.>"
          ] },  
        subscribe: { allow: [
          "$JS.ACK.>"
          "$JS.L3.API.INFO"
          "$JS.L3.API.CONSUMER.INFO.TELEMETRY.l3-c0"
          "$JS.L3.API.CONSUMER.MSG.NEXT.TELEMETRY.l3-c0"  

#          "$JS.L3.API.CONSUMER.RESET.TELEMETRY.l3-c0"
#          "$JS.L3.API.CONSUMER.PAUSE.TELEMETRY.l3-c0"
          ] } } 
      }

    ]
  }
}
