port: 4252
http_port: 8252

server_name: l3-mux

cluster: {
  name: L3
}

leafnodes {
  remotes [
    { urls: ["nats-leaf://l:x@localhost:7422"], account: EDGE }
  ]
}

accounts: {
  EDGE: {
    users: [
      { user: e, password: x }
    ]
  }
}
