port: 4222
http_port: 8222

server_name: hub

cluster: {
  name: HUB
}

leafnodes {
  port: 7422
  isolate: true
}

jetstream {
  store_dir: "./js/hub"
  domain: "HUB"
}

accounts: {
  APP: {
    jetstream:true
    users: [ 
      { user: a, password: x }

      { user: l1, password:x, permissions: { 
        publish: { allow: [
          "$JSC.R.>"
          "$JS.S.>"
          ] },  
        subscribe: { allow: [
          "$JS.FC.>"
          "$JS.L1.API.CONSUMER.RESET.TELEMETRY.>"
          ] } } 
      }
      
      { user: l2, password:x, permissions: { 
        publish: { allow: [
          "$JSC.R.>"
          "$JS.S.>"
          ] },  
        subscribe: { allow: [
          "$JS.FC.>"
          "$JS.L2.API.CONSUMER.RESET.TELEMETRY.>"
          ] } } 
      }

      { user: l3, password:x, permissions: { 
        publish: { allow: [
          "$JSC.R.>"
          "$JS.S.>"
          ] },  
        subscribe: { allow: [
          "$JS.FC.>"
          "$JS.L3.API.CONSUMER.RESET.TELEMETRY.>"
          ] } } 
      }

    ]
  }
}
