port: 4242
http_port: 8242

server_name: l2

cluster: {
  name: L2
}

leafnodes {
  port: 7442
}

accounts: {
  EDGE: {
    users: [ 
      { user: e, password: x }
      { user: el, password: x }
    ]
  }
  SYS: {
    users: [ 
      { user: s, password: x }
      { user: sl, password: x }
    ]
  }
}
system_account: SYS
