port: 4222
http_port: 8222

server_name: hub

cluster: {
  name: HUB
}

leafnodes {
  port: 7422
  isolate: true
}

accounts: {
  APP: {
    users: [ 
      { user: a, password: x }

      { user: l1, password:x, permissions: { publish: { allow: [ "l2h.>", "_INBOX.>", "lx2h.L1.>" ] }, subscribe: { allow: [ "h2l.>", "h2lx.L1.>", "h2lx.ALL.>" ] } } }
      { user: l2, password:x, permissions: { publish: { allow: [ "l2h.>", "_INBOX.>", "lx2h.L2.>" ] }, subscribe: { allow: [ "h2l.>", "h2lx.L2.>", "h2lx.ALL.>" ] } } }
      { user: l3, password:x, permissions: { publish: { allow: [ "l2h.>", "_INBOX.>", "lx2h.L3.>" ] }, subscribe: { allow: [ "h2l.>", "h2lx.L3.>", "h2lx.ALL.>" ] } } }
    ]
    mappings: {
      "edge.>" "h2lx.ALL.>"
    }
  }
}
