port: 4252
http_port: 8252

server_name: l3

cluster: {
  name: L3
}

leafnodes {
  remotes [
    { urls: ["nats-leaf://l3:x@localhost:7422"], account: EDGE, deny_exports: [ "edge.>" ], deny_imports: [ "edge.>" ] }
  ]
}

accounts: {
  EDGE: {
    jetstream:true
    users: [ 
      { user: e, password: x }
    ]
    mappings: {
      "h2lx.L3.>" "edge.>" 
      "h2lx.ALL.>" "edge.>"

      "lx2h.>" "lx2h.L3.>"
    }
  }
}
