port: 4222
http_port: 8222

server_name: hub

cluster: {
  name: HUB
}

leafnodes {
  port: 7422
  isolate: true
}

jetstream {
  store_dir: "./js/hub"
}

accounts: {
  APP: {
    jetstream:true
    users: [ 
      { user: a, password: x }
      { user: l, password: x, permissions: { publish: { deny: ["telemetry.>"] } } }
    ]
  }
}
