port: 4232
http_port: 8232

server_name: l1

cluster: {
  name: L1
}

leafnodes {
  remotes [
    { urls: ["nats-leaf://l:x@localhost:7422"], account: EDGE }
  ]
}

jetstream {
  store_dir: "./js/l1"
  domain: "L"
}

accounts: {
  EDGE: {
    jetstream:true
    users: [ 
      { user: e, password: x }
    ]
  }
}
