port: 4252
http_port: 8252

server_name: l3

cluster: {
  name: L3
}

leafnodes {
  remotes [
    { urls: ["nats-leaf://l:x@localhost:7422"], account: EDGE }
  ]
}

jetstream {
  store_dir: "./js/l3"
}

accounts: {
  EDGE: {
    jetstream:true
    users: [ 
      { user: e, password: x }
    ]
  }
}
