port: 4242
http_port: 8242

server_name: l2

cluster: {
  name: L2
}

leafnodes {
  port: 7432
}

accounts: {
  EDGE: {
    users: [ 
      { user: e, password: x }
      { user: l, password: x }
    ]
  }
}
