port: 4232
http_port: 8232

server_name: l1

cluster: {
  name: L1
}

leafnodes {
  remotes [
    { urls: ["nats-leaf://l:x@localhost:7422"], account: EDGE }
    { urls: ["nats-leaf://sl:x@localhost:7422"], account: SYS }
  ]
}

accounts: {
  EDGE: {
    users: [ 
      { user: e, password: x }
    ]
  }
  SYS: {
    users: [ 
      { user: s, password: x }
    ]
  }
}
system_account: SYS
